# Generated by Django 4.2.5 on 2025-09-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("treino", models.CharField(max_length=80)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completo", "Completo"),
                            ("Pendente", "Pendente"),
                            ("Em Andamento", "Em Andamento"),
                        ],
                        default="Pendente",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Aluno",
                "ordering": ["nome"],
            },
        ),
    ]
