# Generated by Django 5.2 on 2025-09-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('Completo', 'Completo'), ('Pendente', 'Pendente'), ('Em ndamento', 'Em Andamento')], default='Pendente', max_length=12),
        ),
    ]
