# Generated by Django 4.2.5 on 2025-09-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medidas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "altura",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Altura (m)"
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso (kg)"
                    ),
                ),
                (
                    "cintura",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Cintura (cm)"
                    ),
                ),
                (
                    "quadril",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Quadril (cm)"
                    ),
                ),
                (
                    "braco_direito",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Braço Direito (cm)",
                    ),
                ),
                (
                    "braco_esquerdo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Braço Esquerdo (cm)",
                    ),
                ),
                (
                    "coxa_direita",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Coxa Direita (cm)"
                    ),
                ),
                (
                    "coxa_esquerda",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Coxa Esquerda (cm)",
                    ),
                ),
                (
                    "panturrilha_direita",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Panturrilha Direita (cm)",
                    ),
                ),
                (
                    "panturrilha_esquerda",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Panturrilha Esquerda (cm)",
                    ),
                ),
                (
                    "peito",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peito (cm)"
                    ),
                ),
                (
                    "largura_ombros",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Largura dos Ombros (cm)",
                    ),
                ),
                (
                    "data_medida",
                    models.DateField(auto_now_add=True, verbose_name="Data da Medida"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="paginas.aluno"
                    ),
                ),
            ],
        ),
    ]
