# Generated by Django 5.2 on 2025-11-02 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0001_initial'),
        ('usuarios', '0002_remove_professor_aluno_aluno_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidas',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno'),
        ),
    ]
