# Generated by Django 5.2 on 2025-09-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medida',
            name='aluno',
        ),
    ]
