# Generated by Django 5.2 on 2025-09-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Exercício')),
                ('descricao', models.TextField(verbose_name='Descrição do Exercício')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treino.categoria', verbose_name='Categoria do Exercício')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_treino', models.CharField(max_length=100, verbose_name='Nome do Treino')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('descricao', models.TextField(verbose_name='Descrição do Treino')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno', verbose_name='Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ExercicioTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(verbose_name='Número de Séries')),
                ('repeticoes', models.PositiveIntegerField(verbose_name='Número de Repetições')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treino.exercicio', verbose_name='Exercício')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treino.treino', verbose_name='Treino')),
            ],
        ),
    ]
