# Generated by Django 4.2.5 on 2025-09-26 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Categoria"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Exercício"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Exercício")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="treino.categoria",
                        verbose_name="Categoria do Exercício",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_treino",
                    models.CharField(max_length=100, verbose_name="Nome do Treino"),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data de Fim"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Treino")),
                (
                    "cadastrado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.aluno",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treinos_principais_cadastrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado por",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExercicioTreino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series",
                    models.PositiveIntegerField(verbose_name="Número de Séries"),
                ),
                (
                    "repeticoes",
                    models.PositiveIntegerField(verbose_name="Número de Repetições"),
                ),
                (
                    "cadastrado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercicios_treinos_cadastrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado por",
                    ),
                ),
                (
                    "exercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="treino.exercicio",
                        verbose_name="Exercício",
                    ),
                ),
                (
                    "treino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treino.treino",
                        verbose_name="Treino",
                    ),
                ),
            ],
        ),
    ]
