# Generated by Django 4.2.23 on 2025-10-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treino", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciciotreino",
            name="descanso",
            field=models.IntegerField(
                default=1, verbose_name="Descanso entre as séries"
            ),
            preserve_default=False,
        ),
    ]
