# Generated by Django 5.2 on 2025-11-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0002_exerciciotreino_descanso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciotreino',
            name='descanso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Descanso entre as séries'),
        ),
    ]
