# Generated by Django 5.2 on 2025-11-18 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0003_alter_exerciciotreino_descanso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='exercicio',
            options={'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercícios'},
        ),
        migrations.AlterModelOptions(
            name='exerciciotreino',
            options={'verbose_name': 'Exercício do Treino', 'verbose_name_plural': 'Exercícios dos Treinos'},
        ),
        migrations.AlterModelOptions(
            name='treino',
            options={'verbose_name': 'Treino', 'verbose_name_plural': 'Treinos'},
        ),
        migrations.CreateModel(
            name='HistoricoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(default=1)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('tipo_alteracao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('exercicio_add', 'Exercício Adicionado'), ('exercicio_rem', 'Exercício Removido'), ('exercicio_edit', 'Exercício Editado')], max_length=50)),
                ('descricao_alteracao', models.TextField()),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='treino.treino')),
            ],
            options={
                'verbose_name': 'Histórico de Treino',
                'verbose_name_plural': 'Históricos de Treinos',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
