# Generated by Django 4.2.5 on 2025-09-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, verbose_name="Nome do Aluno"),
                ),
                ("idade", models.IntegerField(verbose_name="Idade do Aluno")),
                (
                    "telefone",
                    models.CharField(max_length=10, verbose_name="Telefone do Aluno"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email do Aluno"),
                ),
                (
                    "objetivo",
                    models.CharField(max_length=100, verbose_name="Objetivo do Aluno"),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, verbose_name="Status do Aluno (Ativo/Inativo)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=30, verbose_name="Nome da Cidade"),
                ),
                (
                    "estado",
                    models.CharField(max_length=30, verbose_name="Nome do Estado"),
                ),
                (
                    "sigla",
                    models.CharField(max_length=2, verbose_name="Sigla do Estado"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=30, verbose_name="Nome do Estado"),
                ),
                (
                    "sigla",
                    models.CharField(max_length=2, verbose_name="Sigla do Estado"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, verbose_name="Nome do Professor"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email do Professor"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(max_length=11, verbose_name="CPF do Professor"),
                ),
                (
                    "login",
                    models.CharField(max_length=20, verbose_name="Login do Professor"),
                ),
                (
                    "senha",
                    models.CharField(max_length=20, verbose_name="Senha do Professor"),
                ),
            ],
        ),
    ]
