# Generated by Django 4.2.5 on 2025-09-26 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, verbose_name="Nome do Aluno"),
                ),
                ("idade", models.IntegerField(verbose_name="Idade do Aluno")),
                (
                    "cpf",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="CPF do Aluno"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(max_length=10, verbose_name="Telefone do Aluno"),
                ),
                (
                    "objetivo",
                    models.CharField(max_length=400, verbose_name="Objetivo do Aluno"),
                ),
                (
                    "data_criacao",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ativo", "Ativo"),
                            ("Inativo", "Inativo"),
                            ("Pendente", "Pendente"),
                        ],
                        default="Ativo",
                        max_length=12,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Feminino", "Feminino"),
                            ("Outro", "Outro"),
                        ],
                        default="Outros",
                        max_length=10,
                        verbose_name="Sexo do Aluno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=30, verbose_name="Nome da Cidade"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=30, verbose_name="Nome do Estado"),
                ),
                (
                    "sigla",
                    models.CharField(max_length=2, verbose_name="Sigla do Estado"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, verbose_name="Nome do Professor"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=11, verbose_name="CPF do Professor"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usuarios.aluno",
                        verbose_name="Alunos do Professor",
                    ),
                ),
                (
                    "cidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="usuarios.cidade",
                        verbose_name="Cidade do Professor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professores_cadastrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário do Professor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cidade",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="usuarios.estado",
                verbose_name="Estado",
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="cidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="usuarios.cidade",
                verbose_name="Cidade do Aluno",
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alunos_cadastrados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário do Aluno",
            ),
        ),
    ]
