# Generated by Django 4.2.5 on 2025-09-11 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cidade",
            name="sigla",
        ),
    ]
