# Generated by Django 4.2.23 on 2025-10-06 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="aluno",
        ),
        migrations.AddField(
            model_name="aluno",
            name="professor",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meus_alunos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Professor do Aluno",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professor",
            name="telefone",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=11,
                verbose_name="Telefone do Cliente",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aluno",
            name="data_criacao",
            field=models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="perfi_aluno",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário do Aluno",
            ),
        ),
    ]
