# Generated by Django 5.2 on 2025-09-14 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0002_remove_medida_aluno'),
        ('usuarios', '0002_remove_cidade_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='login',
            field=models.CharField(max_length=20, null=True, verbose_name='Login do Aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='medidas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medidas.medida', verbose_name='Medidas do Aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='senha',
            field=models.CharField(max_length=20, null=True, verbose_name='Senha do Aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='Outros', max_length=10, verbose_name='Sexo do Aluno'),
        ),
        migrations.AddField(
            model_name='professor',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.aluno', verbose_name='Alunos do Professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='login',
            field=models.CharField(max_length=20, null=True, verbose_name='Login do Professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='senha',
            field=models.CharField(max_length=20, null=True, verbose_name='Senha do Professor'),
        ),
    ]
