# Generated by Django 4.2.5 on 2025-09-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_aluno_login_aluno_medidas_aluno_senha_aluno_sexo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="medidas",
        ),
        migrations.AlterField(
            model_name="aluno",
            name="objetivo",
            field=models.CharField(max_length=400, verbose_name="Objetivo do Aluno"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ativo", "Ativo"),
                    ("Inativo", "Inativo"),
                    ("Pendente", "Pendente"),
                ],
                default="Pendente",
                max_length=12,
                null=True,
            ),
        ),
    ]
