# Generated by Django 4.2.5 on 2025-09-19 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0004_remove_aluno_medidas_alter_aluno_objetivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="data_medida",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data da Medida"
            ),
        ),
    ]
