# Generated by Django 4.2.5 on 2025-09-19 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0005_aluno_data_medida"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="data_medida",
        ),
        migrations.AddField(
            model_name="aluno",
            name="data_criacao",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data de Criação"
            ),
        ),
    ]
