# Generated by Django 4.2.20 on 2025-06-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("telefone", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name_plural": "Nome",
                "ordering": ["nome"],
            },
        ),
    ]
