# Generated by Django 5.2 on 2025-09-02 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Estado')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla do Estado')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(default=18, verbose_name='Idade do Aluno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email do Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome do Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(max_length=10, verbose_name='Telefone do Aluno'),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome da Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aluno.estado', verbose_name='Estado')),
            ],
        ),
    ]
